{% set name = "xradar" %}
{% set version = "0.6.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xradar-{{ version }}.tar.gz
  sha256: 06a61f02b1cc867e354c57f7ed7388ca571ab290b83c407bfae322a1cee2ce6a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >=3.9
    - packaging
    - cmweather
    - dask
    - h5netcdf
    - h5py
    - lat_lon_parser
    - numpy
    - netcdf4
    - python-dateutil
    - scipy
    - xarray <=2024.9.0
    - xarray-datatree >=0.0.14
    - xmltodict
    - pyproj

test:
  imports:
    - xradar
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/openradar/xradar
  summary: Xradar includes all the tools to get your weather radar into the xarray data model.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kmuehlbauer
    - mgrover1
