{% set name = "xradar" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xradar-{{ version }}.tar.gz
  sha256: 84209b095d00b0c2ba941c28f6e328b0475d45e1695ed5c8e645440159f2975c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools_scm
  run:
    - python >=3.9
    - packaging
    - cmweather
    - dask
    - h5netcdf
    - h5py
    - lat_lon_parser
    - numpy
    - netcdf4
    - python-dateutil
    - scipy
    - xarray
    - xarray-datatree >=0.0.10
    - xmltodict
    - pyproj

test:
  imports:
    - xradar
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/openradar/xradar
  summary: Xradar includes all the tools to get your weather radar into the xarray data model.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kmuehlbauer
    - mgrover1
