{% set name = "xradar" %}
{% set version = "0.0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xradar-{{ version }}.tar.gz
  sha256: 5518225d06ddae66a4222c628e793addb51205722b402a49a7ff8d82fc27169f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - packaging
    - dask
    - h5netcdf
    - h5py
    - lat_lon_parser
    - numpy
    - netcdf4
    - python-dateutil
    - scipy
    - xarray
    - xarray-datatree >=0.0.10
    - xmltodict

test:
  imports:
    - xradar
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/openradar/xradar
  summary: Xradar includes all the tools to get your weather radar into the xarray data model.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kmuehlbauer
    - mgrover1
