{% set name = "xradar" %}
{% set version = "0.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xradar-{{ version }}.tar.gz
  sha256: 21ff293249ac0501b0b3993f6ab46e1315f36cb0696bef59190ecce845eb25b0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - packaging
    - dask
    - h5netcdf
    - h5py
    - lat_lon_parser
    - numpy
    - netcdf4
    - python-dateutil
    - xarray
    - xarray-datatree
    - xmltodict

test:
  imports:
    - xradar
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/openradar/xradar
  summary: Xradar includes all the tools to get your weather radar into the xarray data model.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kmuehlbauer
    - mgrover1
