{% set name = "xradar" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xradar-{{ version }}.tar.gz
  sha256: 7872d6901ad114cbbd948d7d25870ee80a172448bed720d65ba0003405bda712

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - packaging
    - dask
    - h5netcdf
    - h5py
    - numpy
    - netcdf4
    - xarray
    - xarray-datatree

test:
  imports:
    - xradar
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/openradar/xradar
  summary: Xradar includes all the tools to get your weather radar into the xarray data model.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kmuehlbauer
    - mgrover1
