{% set name = "xradar" %}
{% set version = "0.10.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xradar-{{ version }}.tar.gz
  sha256: 5f36ac381a9c05087acb56fa9669e8bd3c7abe8ef80e7fc289e06d07fa08550b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - packaging
    - cmweather
    - dask
    - h5netcdf
    - h5py
    - lat_lon_parser
    - numpy
    - netcdf4
    - python-dateutil
    - scipy
    - xarray >=2024.10.0
    - xmltodict
    - pyproj

test:
  imports:
    - xradar
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/openradar/xradar
  summary: Xradar includes all the tools to get your weather radar into the xarray data model.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kmuehlbauer
    - mgrover1
